services:
  mern-social:
    image: mern-social-mern-social:latest
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - JWT_SECRET=your_secret_key
      - MONGODB_URI=mongodb://172.18.0.1:27017/mernproject
